name: wine-quality-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
    - mlflow
    - dagshub
    - scikit-learn
    - pandas
    - numpy
    - matplotlib
    - seaborn